apiVersion: v1
kind: PersistentVolume
metadata:
  name: concrete-images-pv-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfsCIP }}
    path: "/"