apiVersion: v1
kind: Service
metadata:
  name: concrete-image-gallery-svc-lb
spec:
  selector:
    app: concrete-image-gallery-pod
  ports:
  - protocol: "TCP"
    port: 5051
    targetPort: 5051
  type: LoadBalancer