apiVersion: v1
kind: Service
metadata:
  name: crack-detection-svc-lb
spec:
  selector:
    app: crack-detection-pod
  ports:
  - protocol: "TCP"
    port: 5050
    targetPort: 5050
  type: LoadBalancer