apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-depl
spec:
  selector:
    matchLabels:
      app: image-upload-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: image-upload-pod
    spec:
      volumes:
        - name: concrete-images-pv-nfs
          persistentVolumeClaim:
            claimName: concrete-images-pvc-nfs
      containers:
        - name: image-upload-pod
          image: "{{ .Values.global.imageUploadImage }}"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/app/uploads/images"
              name: concrete-images-pv-nfs      
          ports:
          - containerPort: 3000

